@startuml
/'
unix.puml -- Finite state machine diagram for the Unix DSV parser.

Copyright (C) 2021 Artyom V. Poptsov <poptsov.artyom@gmail.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with the program.  If not, see <http://www.gnu.org/licenses/>.
'/

skinparam state {
  BackgroundColor<<Error>> Orange
}

state "read-escaped-char" as read_escaped_char
state "append-field" as append_field
state "append-last-field" as append_last_field
state "append-row"   as append_row
state "skip-comment" as skip_comment
state "ERROR" as ERROR <<Error>>

/' fsm-read '/
[*] --> read
read --> append_last_field: eof-object?
read --> skip_comment: comment-symbol?
read --> append_row:   (or carriage-return? linefeed?)
read --> append_field: delimiter?
read --> read_escaped_char: backslash?
read -> read: regular-symbol?

/' fsm-append-last-field '/
append_last_field --> [*]

/' fsm-skip-commend '/
skip_comment --> read: (or carriage-return? linefeed?)
skip_comment --> read: regular-symbol?

/' fsm-append-row '/
append_row --> read

/' fsm-append-field '/
append_field --> read

/' fsm-read-escaped-char '/
read_escaped_char --> read

@enduml