name: GNU Guile 2.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install guile-2.2 guile-2.2-libs guile-library
          sudo apt install guile-2.2-dev texinfo help2man
          sudo apt install automake autoconf

      - name: Install Guile-SMC
        run: |
          git clone https://github.com/artyom-poptsov/guile-smc
          cd guile-smc
          git checkout v0.6.2
          autoreconf -vif
          ./configure --with-guilesitedir=/usr/share/guile/site/2.2 --prefix=/usr
          sudo make -j2 install

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Autoreconf
        run: autoreconf -vif

      - name: Configure
        run: ./configure

      - name: Run tests
        run: make check

